### ISSUE TITLE
How to validate Duplicate field with gojsonschema?

### ISSUE THREAD

**Issue by Houlton** [xeipuuv/gojsonschema#204]
This is my json content:
{
    "name" : "tony",
    "name" : "jane"
}
There are two same fields, but Validate OK.

**Comment by handrews** [comment]
Per [RFC 8259](https://tools.ietf.org/html/rfc8259#section-4), the behavior of duplicate fields is undefined.

Per the [latest JSON Schema draft](https://tools.ietf.org/html/draft-handrews-json-schema-01#section-4.2.1), objects in the JSON Schema _data model_ cannot have multiple keys, so the behavior for a JSON _document_ with multiple keys is undefined.

**Comment by Houlton** [comment]
Hi,
So, I can't use gojsonschema to detect multiple keys, am I right?

**Comment by handrews** [comment]
@Houlton you cannot use any conforming JSON Schema implementation to detect multiple keys.  Multiple keys are not an interoperable feature of JSON and therefore they are not covered by the *specification*.  All implementations should have this limitation, because the IETF JSON working group that produced RFC 8259 and its predecessors chose not to address duplicate keys in an interoperable way.  JSON Schema therefore does not have any reliable way to detect or otherwise interact with them.

**Comment by Houlton** [comment]
Got it . Thank you very much for your explanation.
