### ISSUE TITLE
Json schema validation multipleof - not working

### ISSUE THREAD

**Issue by VimalKumarS** [xeipuuv/gojsonschema#223]
Using golang version 1.11
have json schema as follow
{
    "$id": "table1__1",
    "type": "object",
    "title": "table1__1",
    "$schema": "http://json-schema.org/draft-07/schame#",
    "required": [
    ],
    "properties": {
      "col2": {
        "type": "number",
        "default": "",
        "multipleOf": .001
      } 
    },
    "additionalProperties": false
  }

for input json
{
        "col2": 2.001 
    }

- Returns error Must be multiple of 0.001

**Comment by johandorland** [comment]
Ok, turns out I should've read the go docs better and used `big.Rat` instead of `big.Float`.  `big.Float` solved most peoples `multipleOf` issues before, but they are not arbitrary precision as I assumed, whereas `big.Rat` are as they use fractions. 

The solution seems pretty easy so I'll have a fix up soon.
