### ISSUE TITLE
Error field being displayed as (root)

### ISSUE THREAD

**Issue by golthitarun** [xeipuuv/gojsonschema#225]
Hi, I was trying to print the validation errors, i tried using the error.String and also tried to use the error.Field() to get the field name but I get the field name as (root), not sure why is this happening.

Example:
(root): TestField is required

**Comment by golthitarun** [comment]
Hi thanks for the response, the error I am referring to here is the "gojsonschema.ResultError", for this when I run the validation in my local environment I get the expected error response like -> "TestField: TestField is required" but for the same code in a different environment I get -> "(root): TestField is required", I am not sure if there has been any recent update which is affecting this change, if so how can I access the Field from this error object.

**Comment by johandorland** [comment]
I disagree with your expected output. The `err.Field()` method (which subsequently is used by `err.String()`  ) points to the place in the JSON document where the error occurred. TestField is missing and does not exist in the document, the error can not point to something non-existent. The root object is missing a field named TestField and therefore `err.Field()` should point to the root object. This behaviour is consistent with other JSON schema implementations.

**Comment by golthitarun** [comment]
makes sense thank you

**Comment by antoniomtz** [comment]
@golthitarun is correct. I'm using a version og gojsonschema from around Mar 22, 2018 and it does provide the following error output for required fields:
"TestField: TestField is required"
After an upgrade, all of our unit test are failing due to a recent change where the output is (root): TestField is required.

@johandorland can you provide some feedback on this?

Thanks.

**Comment by johandorland** [comment]
@antoniomtz gojsonschema returning `TestField: TestField is required` was a [bug](https://github.com/xeipuuv/gojsonschema/issues/187), which was fixed on [17 October 2018](https://github.com/xeipuuv/gojsonschema/pull/218). I'm sorry that it broke your unit tests, but in these cases when there are bugs in the output of gojsonschema I'm not going to keep the faulty behaviour for the sake of output stability.

The reason why the current output is the correct is outlined pretty well in this issue and in #187. Maybe you could even argue that `(root)` should be removed as I mentioned above, but I don't feel very strongly about that in any way.

**Comment by antoniomtz** [comment]
@johandorland  Thanks for the feedback, I read all previous threads. And I agree with the fix, since it was not showing the right place of the "required field". 

However, do you agree that err.Field() should return the Field that is failing, and adding a new method, perhaps err.Place() should return the place in the json object ?

We have custom error messages and now they are showing this, for "required field" errors:

> {
>  "field": "(root)",
>  "errortype": "required",
>  "description": "Name is required"
> }

Right now, for "required field" error, there is no method that easily returns the field that is missing unless we parse the err.Description() but that looks like a poor workaround to me.

Even (root).Name should be fine. What do you think?

**Comment by johandorland** [comment]
@antoniomtz I don't think having both `err.Field()` and `err.Place()` would add much value. There are only a couple of edge cases where `err.Field()` and `err.Place()` would be different, the required keyword being one of them, and the API is cluttered enough as it is already.

In my opinion `err.Field()` should behave exactly as you describe `err.Place()` already.

As to your problem you can retrieve the missing field with `err.Details()["property"]`.

**Comment by antoniomtz** [comment]
@johandorland thanks, that worked!
