### ISSUE TITLE
Strings passing as integers using map

### ISSUE THREAD

**Issue by j** [xeipuuv/gojsonschema#41]
My schema.json:
```json
{
	"title": "Example Schema",
	"type": "object",
	"properties": {
		"firstName": {
			"type": "string"
		},
		"lastName": {
			"type": "string"
		}
	}
}
```

This shouldn't be valid:
```go
package main

import (
	"fmt"

	"github.com/xeipuuv/gojsonschema"
)

func main() {
	schemaDocument, _ := gojsonschema.NewJsonSchemaDocument("file:///schema.json")

	// Creating the map with integer values validates (INCORRECT)
	jsonDocument := map[string]interface{}{
		"firstName": 1, // this passes and shouldn't
		"lastName":  1.337, // this fails
	}

	// ...
}
```

Unmarshalling json into interface works:
```go
package main

import (
	"fmt"

	"github.com/xeipuuv/gojsonschema"
)

func main() {
	schemaDocument, _ := gojsonschema.NewJsonSchemaDocument("file:///schema.json")

	// The below shows that both fields are invalid (CORRECT)
	var jsonDocument interface{}
	_ = json.Unmarshal([]byte(`{"firstName": 1, "lastName": 1.337}`), &jsonDocument)

	// ...
}
```

I noticed this the first few minutes of playing with this library.  I haven't dug into the code to contribute a fix, so hopefully someone who is more versed can let me know if I'm way off on this.

**Comment by xeipuuv** [comment]
Hi j, 

Thanks for pinpointing the issue.

What happens here is that when using maps, the underlying data becomes "non strict" JSON and causes issues with the reflection library and the field gets ignored.

In your example "firstName": 1 gives an Int, instead of a Float64 expected by JSON standards.

As a quickfix on your side you could force "firstName": Float(1), and in that case it works.

From the library side, i see two options:
1 - Extending the valid types so that it virtually accepts ANY go type.
2 - Force the input to be strict JSON and return an error if it is not the case.

I will work on it.

**Comment by xeipuuv** [comment]
I think i have found a better solution, actually.
The user-defined maps are converted to proper JSON before validation. Check the lastest update :)
